package judge0


type Language struct {
	ID int `json:"id"`
	Name string `json:"name"`
}

type Status struct {
	ID int `json:"id"`
	Description string `json:"description"`

}


const (
	IN_QUEUE = 1
	PROCESSING = 2
	ACCEPTED = 3
	WRONG_ANSWER = 4
	TIME_LIMIT_EXCEEDED = 5
	COMPILATION_ERROR = 6
	RUNTIME_ERROR_SIGSEGV = 7
	RUNTIME_ERROR_SIGXFSZ = 8
	RUNTIME_ERROR_SIGFPE = 9
	RUNTIME_ERROR_SIGABRT = 10
	RUNTIME_ERROR_NZEC = 11
	RUNTIME_ERROR_OTHER = 12
	INTERNAL_ERROR = 13
	EXEC_FORMAT_ERROR = 14
)

var statusMap = map[int]string{
	IN_QUEUE:              "IN_QUEUE",
	PROCESSING:            "PROCESSING",
	ACCEPTED:              "ACCEPTED",
	WRONG_ANSWER:          "WRONG_ANSWER",
	TIME_LIMIT_EXCEEDED:   "TIME_LIMIT_EXCEEDED",
	COMPILATION_ERROR:     "COMPILATION_ERROR",
	RUNTIME_ERROR_SIGSEGV: "RUNTIME_ERROR_SIGSEGV",
	RUNTIME_ERROR_SIGXFSZ: "RUNTIME_ERROR_SIGXFSZ",
	RUNTIME_ERROR_SIGFPE:  "RUNTIME_ERROR_SIGFPE",
	RUNTIME_ERROR_SIGABRT: "RUNTIME_ERROR_SIGABRT",
	RUNTIME_ERROR_NZEC:    "RUNTIME_ERROR_NZEC",
	RUNTIME_ERROR_OTHER:   "RUNTIME_ERROR_OTHER",
	INTERNAL_ERROR:        "INTERNAL_ERROR",
	EXEC_FORMAT_ERROR:     "EXEC_FORMAT_ERROR",
}

